"""phone1

Revision ID: 0aa01e19bced
Revises: 6a87fdb34e4f
Create Date: 2019-04-24 17:44:54.998646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa01e19bced'
down_revision = '6a87fdb34e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone1', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone1')
    # ### end Alembic commands ###
