"""phone2

Revision ID: 43b6fe0d4a19
Revises: 0aa01e19bced
Create Date: 2019-04-24 17:45:25.727044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b6fe0d4a19'
down_revision = '0aa01e19bced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone2')
    # ### end Alembic commands ###
