"""orderItem

Revision ID: a2ae10b9cb7e
Revises: 2af6f9ccd776
Create Date: 2019-04-11 17:36:42.608806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2ae10b9cb7e'
down_revision = '2af6f9ccd776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('coupon_code', sa.String(length=10), nullable=False),
    sa.Column('coupon_img', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('order', 'coupon_img')
    op.drop_column('order', 'coupon_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('coupon_code', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('order', sa.Column('coupon_img', mysql.VARCHAR(length=128), nullable=False))
    op.drop_table('order_item')
    # ### end Alembic commands ###
