"""empty message

Revision ID: a377ceb4a071
Revises: fded8f3bf60e
Create Date: 2019-04-04 16:52:30.474936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a377ceb4a071'
down_revision = 'fded8f3bf60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('can_download', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('user_ip', sa.String(length=20), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('font_size', sa.String(length=10), nullable=True),
    sa.Column('night_mode', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.String(length=128), nullable=True),
    sa.Column('book_name', sa.String(length=128), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('txt_name', sa.String(length=128), nullable=True),
    sa.Column('lock', sa.Boolean(), nullable=True),
    sa.Column('chapter_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.String(length=128), nullable=True),
    sa.Column('book_name', sa.String(length=128), nullable=True),
    sa.Column('chapter_index', sa.Integer(), nullable=True),
    sa.Column('chapter_name', sa.String(length=128), nullable=True),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('source_name', sa.String(length=128), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('is_subscribe', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.String(length=128), nullable=True),
    sa.Column('book_name', sa.String(length=128), nullable=True),
    sa.Column('chapter', sa.String(length=128), nullable=True),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('chapter_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_table('task')
    op.drop_table('subscribe')
    op.drop_table('record')
    op.drop_table('download')
    op.drop_table('user')
    # ### end Alembic commands ###
